### ISSUE TITLE
Repeated fields' name in child form different than non-repeated

### ISSUE THREAD

**Issue by bishopb** [kristijanhusak/laravel4-form-builder#3]
Essential example:

```
class MyForm extends Form {
    public function buildForm() {
        $this->add('foo', 'text');
        $this->add('bar', 'repeated', [ 'type' => 'text', 'first_name' => 'bar', 'second_name' => 'bar_confirm' ]);
   }
}

$child = new MyForm();

$parent = Form::create(...);
$parent->add('child', 'form', [ 'class' => $child ]);
```

The essential rendered output is:

```
<input class="form-control" id="foo" name="parent[foo]" type="text">    
<input class="form-control" id="bar" name="bar" type="text">    
<input class="form-control" id="bar_confirm" name="bar_confirm" type="text">    
```

Expecting all inputs to be named in "parent" space, ie: `parent[bar]` and `parent[bar_confirm]`.

**Comment by kristijanhusak** [comment]
Yes, the problem exists. I'm just not sure how is this field type helpful as it is now, i added it long time ago, and didn't test it thoroughly. Just noticed that name it is given (in your example `bar`), is not used at all. That's why the naming is not proper. Same thing can be achieved with a child form.

Can you give me real example where you are using it?

I should update it to use first parameter in `add()` instead of `first_name`, and second to be configured from options like it is now.

**Comment by bishopb** [comment]
I use it on a credentials form, for confirmation of username and password.

"Repeated" was definitely a short-cut. I could have just done:

```
$this->add('username', 'text');
$this->add('username_confirm', 'text');
$this->add('password', 'password');
$this->add('password_confirm', 'password');
```

My actual use case is more complicated, because the form is flexible: the form consumer decides whether he wants to username to require confirmation, or password to require confirmation.  So "repeated" was convenience to keep the code short, given it had more complexity surrounding it.

**Comment by kristijanhusak** [comment]
Yes that was the first idea to use it for confirmation fields. I'll probably update it as i said, to use passed name as first value, and second one to be passed in options, something like this:

``` php
<?php
$this->add('password', 'repeated', [
    'first_options' => [],
    'second_name' => 'password_confirmation' // This would be default
    'second_options' => []
]);
```

Would that work out in your case?

**Comment by bishopb** [comment]
Yes, I think that would work (provided `type` field is there).

Of course, I'm of the opinion that something more consistent with the existing API, like this:

```
<?php
$this->add('username', 'text', [ 'attr' => [ 'class' => 'foo' ]]); // first field
$this->getField('username')->repeat();  // adds second field, repeating with defaults
```

To override those defaults:

```
$this->getField('username')->repeat('username_confirm', 'text', [ 'attr' => [ 'class' => 'bar' ]]);
```

This works a little better in my workflow, because the confirmation field is optional, depending upon form configuration.  So, if confirmation is wanted, it's easy to add it in with a method call.

**Comment by kristijanhusak** [comment]
Honestly, I don't think repeated field type is used that often (probably most of the time only for password confirmation), and especially not to be optional like in your case. 

The `repeat()` method is great idea, but most of these field types are idea from Symfony's form component, and for this type i tried to simulate [this](http://symfony.com/doc/current/reference/forms/types/repeated.html). 

Since it is pretty impossible to do the same thing (use these two fields to bind value to the 3rd field), i'll probably set up `repeated` type to be as described in my last comment. That would not work in your case, because it needs to be optional, but the point of the field type would be achieved. 

I also got an idea about methods `addAfter()` and `addBefore()`, which would allow adding fields at specific locations later.

**Comment by bishopb** [comment]
Works for me, thanks!  I can handle my use case with a branch, making different API calls as needed.

**Comment by kristijanhusak** [comment]
Repeated fields are fixed, and working as described :)

**Comment by bishopb** [comment]
Confirmed, thanks!
